spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portfoliohub}
    username: ${DB_USERNAME:portfoliohub}
    password: ${DB_PASSWORD:portfoliohub}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    clean-disabled: true
server:
  port: 0
